### ISSUE TITLE
Negative feature is not working properly with interest Amount for negative balance

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#153]
**Woo Commerce Version** - 8.2.0
**WordPress Version** - 6.3.2
**Plugin Version** - 2.5.3
**Description** - Negative feature is not working properly with interest Amount for negative balance

[scrnli_27_10_2023_13-59-42.webm](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/99fb1ecd-9365-4d25-a83c-cee9a2d2dd4f)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Still Exist

**Comment by Ananya-Cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Still Exist

[scrnli_01_11_2023_12-50-12.webm](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/0c0a2a7c-6048-4225-a786-bed0c08c0b8e)

**Comment by Ananya-Cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Fixed
