### ISSUE TITLE
user able to enter negative value

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#157]
**Woo Commerce Version** - 8.2.0
**WordPress Version** - 6.3.2
**Plugin Version** - 2.5.3
**Description** - user able to enter negative value
**Note** - Please also check in Wallet action page and Wallet cashback

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/81ec25e3-1703-4679-98bc-992f89ed96e8)

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/8af31cc2-5ab2-4fb5-aec3-7565594e0fd6)

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/41010d0c-f46b-4020-aeb1-be623b1b0472)

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/a62dfe95-9585-4c95-a1fb-2076a66a2fc6)

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/d74b5001-d4fe-4c6c-a1a3-a17f208b42e7)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Still Exist
![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/7477505e-aef5-4988-9eea-39ff7a1c7008)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Still Exist

[scrnli_01_11_2023_12-43-13.webm](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/c0012168-0125-4aaf-952e-ad98be0d71ea)

**Comment by Ananya-Cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Fixed
