### ISSUE TITLE
Wallet recharge page refresh issue

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#159]
**Woo Commerce Version** - 8.2.0
**WordPress Version** - 6.3.2
**Plugin Version** - 2.5.3
**Description** - Wallet recharge page refresh issue

[scrnli_31_10_2023_11-19-36.webm](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/4f573825-2dd7-48dd-8a44-5008ec72bca3)

**Comment by Ananya-Cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Still Exist

[scrnli_01_11_2023_12-36-01.webm](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/4f9088bc-fb9e-4d8f-a6d3-54583efa1418)

**Comment by Ananya-Cedcoss** [comment]
Fixed

**Comment by ashish-wps** [comment]
Fixed
