### ISSUE TITLE
Cashback percentage issue

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#167]
**Woo Commerce Version - 8.3.1
WordPress Version - 6.4.1
Plugin Version - 2.5.5
Description -** Cashback percentage issue

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/37965213-183a-4afe-a249-f58a161491ff)

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/814cab14-806f-45c1-aa46-6ecb1832554e)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Still Exist

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/c16b21c6-9803-4fec-9fe5-744173931132)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
[scrnli_12_12_2023_14-46-46.webm](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/f3694930-ee00-43f7-9967-69feea69e78c)

**Comment by ashish-wps** [comment]
Fixed
