### ISSUE TITLE
Tax Total issue when user enter partial payment

### ISSUE THREAD

**Issue by ashish-wps** [wpswings/wallet-system-for-woocommerce#172]
**Woo Commerce Version - 8.3.1
WordPress Version - 6.4.1
Plugin Version - 2.5.5
Description -** Tax Total issue when user enter partial payment

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/269f4bfb-d6c9-4633-b473-fd284cd5e268)

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/56596405-6e5d-4f6e-a913-43e6ff768f68)

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/32e2d2b6-ef27-4c38-bd60-a1e207f8cc52)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Still Exist
![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/95c160d2-0248-4bcc-abc6-ca91b2439396)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by ashish-wps** [comment]
Fixed

![image](https://github.com/wpswings/wallet-system-for-woocommerce/assets/105413021/fb1efdde-afed-42ef-a304-68357b1e40a8)
