### ISSUE TITLE
If the user has deleted the Transaction list is showing blank in the place of the name

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [wpswings/wallet-system-for-woocommerce#62]
WordPress: 6.0.1
Woocommerce: 6.7.0
Description:
If the user has deleted the Transaction list is showing blank in the place of the name
![image](https://user-images.githubusercontent.com/85384857/180695814-f94a33fb-d32e-4e77-af6a-5a1e69bdf78b.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
Issue Still there
![image](https://user-images.githubusercontent.com/85384857/181225305-505c57b5-02f3-4bd9-bb0f-fbf3ea2b1bcd.png)

**Comment by Ananya-Cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
